export enum Routes {
  LOGIN = "/",
  REGISTER = "/register",
  HOME = "/home",
  STORES = "/stores",
  NEW_STORE = "/stores/new",
  PRODUCTS = "/products",
  NEW_INCOMING = "/transactions/incoming/new",
  SELECT_PRODUCT = "/transactions/incoming/select-product",
  EDIT_PRODUCT = "/products/edit",
  NEW_PRODUCT = "/products/new",
  INCOMING_RECEIPT = "/transactions/incoming/receipt",
  NEW_OUTGOING = "/transactions/outgoing/new",
  SELECT_OUTGOING = "/transactions/outgoing/select-product",
  COLLABORATORS = "/collaborators",
  NEW_COLLABORATOR = "/collaborators/new",
  OUTGOING_RECEIPT = "/transactions/outgoing/receipt",
  EDIT_COLLABORATOR = "/collaborators/edit",
  BARCODE = "/barcode",
  TRANSACTIONS = "/transactions/transactions",

}
